# Generated by Django 3.2.13 on 2022-06-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/'),
        ),
    ]
