# Generated by Django 3.2.13 on 2022-06-28 20:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220628_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Template Slug')),
                ('body_html', ckeditor.fields.RichTextField(verbose_name='Body HTML')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Template',
                'verbose_name_plural': 'Custom Templates',
            },
        ),
    ]
